#!/bin/bash

# default values
version="0.1"
interval=0.1

name=
verbose=

# argument parsing
while true; do
    case "${1}" in
        -n|--name)
            name=1
            declare -A pid
            shift
            ;;
        -v|--verbose)
            verbose=1
            shift
            ;;
        --version)
            echo "version ${version}"
            exit
            ;;
        -*|--*)
            echo "invalid option: ${1}" 1>&2
            exit 1
            ;;
        *)
            if [[ -n "${@}" ]]; then
                pid["${1}"]=1
                shift
            else
                break
            fi
            ;;
    esac
done

unset pid[0]
if [ "${#pid[@]}" -eq 0 ]; then
    echo "usage: $(basename ${0}) [-n|--name] [-v|--verbose] [pid...]" 1>&2
    exit 1
fi

# check pids
if [ ${verbose} ]; then
    echo "monitoring pids: ${!pid[@]}"
fi

function remove_pid {
    unset pid[${1}]
    if [ ${verbose} ]; then
        echo "${1} removed."
    fi
}

while [ "${#pid[@]}" -ne 0 ]; do
    for id in "${!pid[@]}"; do
        if [ ! ${name} ] && [ "${pid[${id}]}" -eq 1 ] && [ ! -e "/proc/${id}" ]; then
            remove_pid ${id}
        elif [ ${name} ] && [ -z "$(pidof ${id})" ]; then
            remove_pid ${id}
        fi
    done
    sleep ${interval}
done

exit
